#!/usr/bin/env bash
#ping an IP
read -r ip_address
mos=$(ping "$ip_address")
if [ -z "$ip_address" ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	x=0
	while((x<5))
	do
		echo "$mos"
		((x++))
	done
fi
