#!/usr/bin/env bash
# using case
mos=1
while((mos<=20))
do
	echo $mos
	case $mos in

		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
		esac
	((mos++))
done
